// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	internal "github.com/dmitrymomot/forge/internal"

	time "time"
)

// SessionStore is an autogenerated mock type for the Store type
type SessionStore struct {
	mock.Mock
}

type SessionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionStore) EXPECT() *SessionStore_Expecter {
	return &SessionStore_Expecter{mock: &_m.Mock}
}

// CountByUserID provides a mock function with given fields: ctx, userID
func (_m *SessionStore) CountByUserID(ctx context.Context, userID string) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountByUserID")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SessionStore_CountByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByUserID'
type SessionStore_CountByUserID_Call struct {
	*mock.Call
}

// CountByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *SessionStore_Expecter) CountByUserID(ctx interface{}, userID interface{}) *SessionStore_CountByUserID_Call {
	return &SessionStore_CountByUserID_Call{Call: _e.mock.On("CountByUserID", ctx, userID)}
}

func (_c *SessionStore_CountByUserID_Call) Run(run func(ctx context.Context, userID string)) *SessionStore_CountByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SessionStore_CountByUserID_Call) Return(_a0 int, _a1 error) *SessionStore_CountByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SessionStore_CountByUserID_Call) RunAndReturn(run func(context.Context, string) (int, error)) *SessionStore_CountByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, s
func (_m *SessionStore) Create(ctx context.Context, s *internal.Session) error {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *internal.Session) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SessionStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type SessionStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - s *internal.Session
func (_e *SessionStore_Expecter) Create(ctx interface{}, s interface{}) *SessionStore_Create_Call {
	return &SessionStore_Create_Call{Call: _e.mock.On("Create", ctx, s)}
}

func (_c *SessionStore_Create_Call) Run(run func(ctx context.Context, s *internal.Session)) *SessionStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*internal.Session))
	})
	return _c
}

func (_c *SessionStore_Create_Call) Return(_a0 error) *SessionStore_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SessionStore_Create_Call) RunAndReturn(run func(context.Context, *internal.Session) error) *SessionStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *SessionStore) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SessionStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type SessionStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *SessionStore_Expecter) Delete(ctx interface{}, id interface{}) *SessionStore_Delete_Call {
	return &SessionStore_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *SessionStore_Delete_Call) Run(run func(ctx context.Context, id string)) *SessionStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SessionStore_Delete_Call) Return(_a0 error) *SessionStore_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SessionStore_Delete_Call) RunAndReturn(run func(context.Context, string) error) *SessionStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUserID provides a mock function with given fields: ctx, userID
func (_m *SessionStore) DeleteByUserID(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SessionStore_DeleteByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUserID'
type SessionStore_DeleteByUserID_Call struct {
	*mock.Call
}

// DeleteByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *SessionStore_Expecter) DeleteByUserID(ctx interface{}, userID interface{}) *SessionStore_DeleteByUserID_Call {
	return &SessionStore_DeleteByUserID_Call{Call: _e.mock.On("DeleteByUserID", ctx, userID)}
}

func (_c *SessionStore_DeleteByUserID_Call) Run(run func(ctx context.Context, userID string)) *SessionStore_DeleteByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SessionStore_DeleteByUserID_Call) Return(_a0 error) *SessionStore_DeleteByUserID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SessionStore_DeleteByUserID_Call) RunAndReturn(run func(context.Context, string) error) *SessionStore_DeleteByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUserIDExcept provides a mock function with given fields: ctx, userID, exceptID
func (_m *SessionStore) DeleteByUserIDExcept(ctx context.Context, userID string, exceptID string) error {
	ret := _m.Called(ctx, userID, exceptID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserIDExcept")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, exceptID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SessionStore_DeleteByUserIDExcept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUserIDExcept'
type SessionStore_DeleteByUserIDExcept_Call struct {
	*mock.Call
}

// DeleteByUserIDExcept is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - exceptID string
func (_e *SessionStore_Expecter) DeleteByUserIDExcept(ctx interface{}, userID interface{}, exceptID interface{}) *SessionStore_DeleteByUserIDExcept_Call {
	return &SessionStore_DeleteByUserIDExcept_Call{Call: _e.mock.On("DeleteByUserIDExcept", ctx, userID, exceptID)}
}

func (_c *SessionStore_DeleteByUserIDExcept_Call) Run(run func(ctx context.Context, userID string, exceptID string)) *SessionStore_DeleteByUserIDExcept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *SessionStore_DeleteByUserIDExcept_Call) Return(_a0 error) *SessionStore_DeleteByUserIDExcept_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SessionStore_DeleteByUserIDExcept_Call) RunAndReturn(run func(context.Context, string, string) error) *SessionStore_DeleteByUserIDExcept_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOldestByUserID provides a mock function with given fields: ctx, userID
func (_m *SessionStore) DeleteOldestByUserID(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOldestByUserID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SessionStore_DeleteOldestByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOldestByUserID'
type SessionStore_DeleteOldestByUserID_Call struct {
	*mock.Call
}

// DeleteOldestByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *SessionStore_Expecter) DeleteOldestByUserID(ctx interface{}, userID interface{}) *SessionStore_DeleteOldestByUserID_Call {
	return &SessionStore_DeleteOldestByUserID_Call{Call: _e.mock.On("DeleteOldestByUserID", ctx, userID)}
}

func (_c *SessionStore_DeleteOldestByUserID_Call) Run(run func(ctx context.Context, userID string)) *SessionStore_DeleteOldestByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SessionStore_DeleteOldestByUserID_Call) Return(_a0 error) *SessionStore_DeleteOldestByUserID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SessionStore_DeleteOldestByUserID_Call) RunAndReturn(run func(context.Context, string) error) *SessionStore_DeleteOldestByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTokenHash provides a mock function with given fields: ctx, tokenHash
func (_m *SessionStore) GetByTokenHash(ctx context.Context, tokenHash string) (*internal.Session, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetByTokenHash")
	}

	var r0 *internal.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*internal.Session, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *internal.Session); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SessionStore_GetByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTokenHash'
type SessionStore_GetByTokenHash_Call struct {
	*mock.Call
}

// GetByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *SessionStore_Expecter) GetByTokenHash(ctx interface{}, tokenHash interface{}) *SessionStore_GetByTokenHash_Call {
	return &SessionStore_GetByTokenHash_Call{Call: _e.mock.On("GetByTokenHash", ctx, tokenHash)}
}

func (_c *SessionStore_GetByTokenHash_Call) Run(run func(ctx context.Context, tokenHash string)) *SessionStore_GetByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SessionStore_GetByTokenHash_Call) Return(_a0 *internal.Session, _a1 error) *SessionStore_GetByTokenHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SessionStore_GetByTokenHash_Call) RunAndReturn(run func(context.Context, string) (*internal.Session, error)) *SessionStore_GetByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function with given fields: ctx, userID
func (_m *SessionStore) ListByUserID(ctx context.Context, userID string) ([]*internal.Session, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []*internal.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*internal.Session, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*internal.Session); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*internal.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SessionStore_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type SessionStore_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *SessionStore_Expecter) ListByUserID(ctx interface{}, userID interface{}) *SessionStore_ListByUserID_Call {
	return &SessionStore_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID)}
}

func (_c *SessionStore_ListByUserID_Call) Run(run func(ctx context.Context, userID string)) *SessionStore_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SessionStore_ListByUserID_Call) Return(_a0 []*internal.Session, _a1 error) *SessionStore_ListByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SessionStore_ListByUserID_Call) RunAndReturn(run func(context.Context, string) ([]*internal.Session, error)) *SessionStore_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Touch provides a mock function with given fields: ctx, id, lastActiveAt
func (_m *SessionStore) Touch(ctx context.Context, id string, lastActiveAt time.Time) error {
	ret := _m.Called(ctx, id, lastActiveAt)

	if len(ret) == 0 {
		panic("no return value specified for Touch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(ctx, id, lastActiveAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SessionStore_Touch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Touch'
type SessionStore_Touch_Call struct {
	*mock.Call
}

// Touch is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - lastActiveAt time.Time
func (_e *SessionStore_Expecter) Touch(ctx interface{}, id interface{}, lastActiveAt interface{}) *SessionStore_Touch_Call {
	return &SessionStore_Touch_Call{Call: _e.mock.On("Touch", ctx, id, lastActiveAt)}
}

func (_c *SessionStore_Touch_Call) Run(run func(ctx context.Context, id string, lastActiveAt time.Time)) *SessionStore_Touch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *SessionStore_Touch_Call) Return(_a0 error) *SessionStore_Touch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SessionStore_Touch_Call) RunAndReturn(run func(context.Context, string, time.Time) error) *SessionStore_Touch_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, s
func (_m *SessionStore) Update(ctx context.Context, s *internal.Session) error {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *internal.Session) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SessionStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type SessionStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - s *internal.Session
func (_e *SessionStore_Expecter) Update(ctx interface{}, s interface{}) *SessionStore_Update_Call {
	return &SessionStore_Update_Call{Call: _e.mock.On("Update", ctx, s)}
}

func (_c *SessionStore_Update_Call) Run(run func(ctx context.Context, s *internal.Session)) *SessionStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*internal.Session))
	})
	return _c
}

func (_c *SessionStore_Update_Call) Return(_a0 error) *SessionStore_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SessionStore_Update_Call) RunAndReturn(run func(context.Context, *internal.Session) error) *SessionStore_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewSessionStore creates a new instance of SessionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionStore {
	mock := &SessionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
