run:
  timeout: 5m

linters:
  default: standard
  enable:
    - goimports
    - misspell
    - unconvert

linters-settings:
  goimports:
    local-prefixes: github.com/dmitrymomot/forge
  misspell:
    ignore-words:
      - elementy

issues:
  exclude-dirs:
    - examples
  exclude-rules:
    - path: _test\.go
      linters:
        - misspell
